import pytest

from gpaw import GPAW, PW
from ase import Atoms
import numpy as np
from gpaw.directmin.etdm_fdpw import FDPWETDM
from gpaw.directmin.tools import excite
from gpaw.mom import prepare_mom_calculation


@pytest.mark.old_gpaw_only
@pytest.mark.sic
def test_mom_pwsic(in_tmp_dir, gpw_files):
    calc = GPAW(gpw_files["h2o_mom_pwsic"])
    H2O = calc.atoms
    H2O.calc = calc
    e = H2O.get_potential_energy()
    f = H2O.get_forces()

    # Numeric forces, generated by disabled code below
    f_num = np.array(
        [
            [-2.85022, -3.66863, -0.009059],
            [3.916824, -0.204146, -0.000065],
            [-1.204687, 3.822242, 0.000353],
        ]
    )
    numeric = False
    if numeric:
        from gpaw.test import calculate_numerical_forces

        f_num = calculate_numerical_forces(H2O, 0.001)
        print("Numerical forces")
        print(f_num)
        print(f - f_num, np.abs(f - f_num).max())

    assert f == pytest.approx(f_num, abs=0.3)
    assert e == pytest.approx(-3.302431, abs=0.2)
