import pytest

from gpaw import GPAW
from ase import Atoms
import numpy as np

@pytest.mark.old_gpaw_only
@pytest.mark.sic
def test_mom_lcaosic(in_tmp_dir, gpw_files):
    calc = GPAW(gpw_files['h2o_mom_lcaosic'])
    H2O = calc.atoms
    H2O.calc = calc
    e = H2O.get_potential_energy()
    f = H2O.get_forces()
    # Saved analytical forces
    f_old = np.array([[-8.76835930e+00, -1.44190257e+01, 2.53281902e-03],
                      [1.46304433e+01, -1.00089622e+00, -1.03430589e-02],
                      [-4.83182230e+00, 1.51551677e+01, -1.20513818e-02]])

    # Numeric forces, generated by disabled code below
    f_num = np.array([[-8.07002033e+00, -1.51005084e+01, -1.67903017e-03],
                      [1.42573640e+01, -9.80976464e-01, 8.86319871e-05],
                      [-4.93107360e+00, 1.54986283e+01, -3.45104541e-03]])

    numeric = False
    if numeric:
        from gpaw.test import calculate_numerical_forces
        f_num = calculate_numerical_forces(H2O, 0.001)
        print('Numerical forces')
        print(f_num)
        print(f - f_num, np.abs(f - f_num).max())

    assert e == pytest.approx(-2.007092, abs=5.0e-3)
    assert f == pytest.approx(f_old, abs=0.5)
    assert f == pytest.approx(f_num, abs=1.0)
